### PR TITLE
Add a discovery section.

### LINKED ISSUE #75: Add a Things Discovery section
Add a section to explain how Thing Descriptions can be discovered. This could include:

- Via a directory of things like a cloud service or things gateway
- Via an mDNS broadcast on a local network (see also https://github.com/mozilla-iot/gateway/issues/696)
- Via a Bluetooth Eddystone beacon broadcast in physical proximity (see also https://github.com/mozilla-iot/gateway/issues/695)

Another possibility is adding HTML link relations to web pages which point to a Thing Description, similar to [`<link rel="manifest">`](https://w3c.github.io/manifest/#using-a-link-element-to-link-to-a-manifest)

### PR DESCRIPTION
**Pull request by mrstegeman**
Fixes #75

### CODE REVIEW

**Comment by mrstegeman** [comment]
@benfrancis please critique.

**Comment by mrstegeman** [comment]
Well, we’ve only ever supported HTTP(S), so that’s just always been assumed. However, CoAP is UDP, so for that, we could instead use `_webthing._udp`.

**Comment by benfrancis** [comment]
> CoAP is UDP, so for that, we could instead use _webthing._udp.

That's fortunate :)

Actually, I've just re-read the discussions in https://github.com/mozilla-iot/wot/issues/75 and https://github.com/mozilla-iot/gateway/issues/696 where it looks I suggested exactly that. I now remember the discussion about sub-types and the discussion about what the service type should be.

Just to complicate matters I've noticed text in the [DNS-SD service types documentation](http://www.dns-sd.org/ServiceTypes.html) says:

> Content types not intended primarily for viewing by a human user, or not widely-supported in web browsing clients, should not be advertised as DNS-SD service type "http", even if they do happen to be transported over HTTP. Such types should be advertised as their own logical service type with their own DNS-SD service type, for example, XUL (XML User Interface Language) transported over HTTP is advertised explicitly as DNS-SD service type "xul-http".

So another option would be webthing-http.

I think this is fine to land as-is as `_webthing._tcp` is totally valid and is documenting what is already implemented. I do anticipate there might be more questions about this if we try to standardise it though.

**Comment by mrstegeman** [comment]
We used to use sub-types but ran into issues with those being unsupported by various libraries. See [here](https://github.com/mozilla-iot/thing-url-adapter/issues/15).

Technically, the Web Thing add-on still supports that scheme, but we don't use it in any of our webthing libraries anymore.

**Comment by benfrancis** [comment]
> We used to use sub-types but ran into issues with those being unsupported by various libraries. See here.

Oh wow, I'd not seen that discussion. Very interesting.

**Pull request merged**
