### PR TITLE
multilevelSwitch, multilevelSensor, smartPlug, onOffLight, dimmableLight and dimmableColorLight types

### PR DESCRIPTION
**Pull request by benfrancis**
Here are three more proposed Web Thing Types which relate to the types we're implementing in version 0.3 of Mozilla's Things Gateway.

These few types are already starting to show the limitations of the current type system with just a single high level "type" for things. We may need to explore an alternative system using "capabilities" which can be mixed and matched between devices.

### CODE REVIEW

**Comment by benfrancis** [comment]
You can see a live HTML version of this [here](https://benfrancis.github.io/wot/#web-thing-types) for readability

**Comment by benfrancis** [comment]
OK, I've added a level field to smartPlug. I've changed coloredDimmableBulb to dimmableColorLight and added onOffLight and dimmableLight as well a multiLevelSensor for completeness.

This maps fairly well onto the ZigBee Home Automation standard which does describe devices types as groups of command clusters in its specification. The one exception is multiLevelSensor which I think Z-Wave has (as a command class) but ZigBee doesn't describe a special device type for. Also the ZigBee Smart Plug doesn't appear to have a level property but there's no special type for a smart plug for a level, so I've just made the level property on smartPlug optional.

There are obviously many different ways to break this down, but this seems a fairly neat set of types for now, until we can come up with a capabilities system which may make it redundant.

**Comment by dhylands** [comment]
ZigBee has the genLevelCtrl cluster which is what the multiLevelSwitch uses.

**Comment by benfrancis** [comment]
OK, I'm going to merge this as a starting point, let's see how we get on with the implementation of these types.

**Pull request merged**
